# Generated by Django 3.1.6 on 2021-02-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=25),
        ),
        migrations.AddField(
            model_name='userbase',
            name='lon',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=25),
        ),
    ]
