# Generated by Django 3.1.6 on 2021-02-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210207_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='magbase',
            name='adress',
            field=models.CharField(default='48 5th Avenue NYC', max_length=200),
        ),
    ]
